[project]
name = "lzhc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "absl-py==1.4.0",
    "aio-pika==9.4.1",
    "aiomysql==0.2.0",
    "aiormq==6.8.0",
    "alembic==1.13.1",
    "altgraph==0.17.4",
    "annotated-types>=0.7.0",
    "anyio==4.3.0",
    "appdirs==1.4.4",
    "apscheduler==3.11.0",
    "array-record==0.4.1",
    "asgiref==3.7.2",
    "astunparse==1.6.3",
    "async-timeout==4.0.3",
    "backtrader==1.9.78.123",
    "beautifulsoup4==4.12.3",
    "cachetools==5.3.3",
    "caffeine==0.5",
    "certifi==2024.2.2",
    "cffi==1.16.0",
    "chardet==5.2.0",
    "charset-normalizer==3.3.2",
    "click>=8.3.1",
    "colorama>=0.4.6",
    "contourpy==1.2.0",
    "cryptography==42.0.5",
    "curl-cffi==0.11.4",
    "cycler==0.12.1",
    "dill==0.3.9",
    "distro==1.9.0",
    "dm-tree==0.1.8",
    "docstring-parser==0.16",
    "dramatiq==1.17.0",
    "etils==1.10.0",
    "exceptiongroup>=1.3.1",
    "fake-useragent==1.5.1",
    "fastapi==0.110.0",
    "fastapi-limiter==0.1.6",
    "fastapi-pagination==0.12.19",
    "filelock==3.13.1",
    "flatbuffers==24.3.25",
    "fonttools==4.50.0",
    "frozendict==2.4.1",
    "fsspec==2024.2.0",
    "func-timeout==4.3.5",
    "gast==0.4.0",
    "google-auth==2.35.0",
    "google-auth-oauthlib==0.4.6",
    "google-pasta==0.2.0",
    "googleapis-common-protos==1.5.6",
    "greenlet==3.0.3",
    "grpcio==1.67.0",
    "h11>=0.16.0",
    "h5py==3.12.1",
    "holiday==1.0.0",
    "holidays==0.59",
    "html5lib==1.1",
    "httpcore>=1.0.9",
    "httptools==0.6.4",
    "httpx>=0.28.1",
    "huggingface-hub==0.36.0",
    "idna==3.6",
    "immutabledict==4.2.1",
    "importlib-resources==6.4.5",
    "jieba==0.42.1",
    "jinja2==3.1.4",
    "jiter==0.11.1",
    "joblib==1.4.2",
    "jsonpath==0.82.2",
    "keras==2.10.0",
    "keras-preprocessing==1.1.2",
    "kiwisolver==1.4.5",
    "libclang==18.1.1",
    "llvmlite==0.43.0",
    "loguru==0.7.2",
    "lxml==5.2.1",
    "mako==1.3.2",
    "markdown==3.7",
    "markupsafe==2.1.5",
    "matplotlib==3.8.3",
    "mpmath==1.3.0",
    "multidict==6.0.5",
    "multitasking==0.0.11",
    "networkx==3.2.1",
    "numba==0.60.0",
    "numpy==1.26.4",
    "oauthlib==3.2.2",
    "objgraph==3.6.2",
    "openai==2.6.1",
    "opt-einsum==3.4.0",
    "packaging==24.0",
    "pamqp==3.3.0",
    "pandas==2.2.1",
    "passlib==1.7.4",
    "path==16.10.0",
    "patsy==0.5.6",
    "peewee==3.17.1",
    "pefile==2023.2.7",
    "pika==1.3.2",
    "pillow==10.2.0",
    "platformdirs==4.3.8",
    "plotly==5.24.1",
    "plotly-express==0.4.1",
    "prettytable==3.11.0",
    "prometheus-client==0.20.0",
    "promise==2.3",
    "protobuf==3.19.6",
    "psutil==6.1.0",
    "py-mini-racer==0.6.0",
    "pyarrow==18.1.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.1",
    "pycparser==2.21",
    "pydantic>=2.12.5",
    "pydantic-core>=2.41.5",
    "pydantic-settings==2.2.1",
    "pydash==7.0.7",
    "pyecharts==2.0.6",
    "pyexecjs==1.5.1",
    "pyinstaller==6.5.0",
    "pyinstaller-hooks-contrib==2024.3",
    "pymysql==1.1.0",
    "pyparsing==3.1.2",
    "pypinyin==0.51.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.9",
    "pytz==2024.1",
    "pywencai==0.12.2",
    "pywin32-ctypes==0.2.2",
    "pyyaml==6.0.2",
    "qstock==1.3.6",
    "redis==5.0.3",
    "regex==2025.10.23",
    "requests==2.31.0",
    "requests-oauthlib==2.0.0",
    "rsa==4.9",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "seaborn==0.13.2",
    "simple-parsing==0.1.6",
    "simplejson==3.19.3",
    "six==1.16.0",
    "sniffio>=1.3.1",
    "soupsieve==2.5",
    "sqlalchemy==2.0.28",
    "starlette==0.36.3",
    "statsmodels==0.14.4",
    "sympy==1.13.1",
    "ta-lib==0.6.4",
    "tenacity==9.0.0",
    "tensorboard==2.10.1",
    "tensorboard-data-server==0.6.1",
    "tensorboard-plugin-wit==1.8.1",
    "tensorflow-estimator==2.10.0",
    "tensorflow-gpu==2.10.1",
    "tensorflow-io-gcs-filesystem==0.31.0",
    "tensorflow-metadata==0.13.0",
    "termcolor==2.5.0",
    "tfds-nightly==4.8.0.dev202212310044",
    "threadpoolctl==3.5.0",
    "tokenizers==0.12.1",
    "toml==0.10.2",
    "torch==2.0.0",
    "torchaudio==2.0.1",
    "torchvision==0.15.1",
    "tqdm==4.66.5",
    "transformers==4.20.1",
    "typing-extensions>=4.15.0",
    "tzdata==2024.1",
    "tzlocal==5.3.1",
    "urllib3==2.2.1",
    "uvicorn==0.28.0",
    "watchfiles==0.24.0",
    "wcwidth==0.2.13",
    "webencodings==0.5.1",
    "websockets==13.1",
    "werkzeug==3.0.6",
    "win32-setctime==1.1.0",
    "wrapt==1.16.0",
    "yarl==1.9.4",
    "yfinance==0.2.63",
    "zipp==3.21.0",
]
